#!/bin/bash
awk '
BEGIN { skip = 0; }
/{[/]\* QUICK MEDICAMENTS PRESETS \(NÍVEL 1 - 2 TOQUES\) - LANÇADOR DE FÁRMACOS \*\// {
  skip = 1;
  print "        {/* QUICK MEDICAMENTS PRESETS (NÍVEL 1 - 2 TOQUES) - LANÇADOR DE FÁRMACOS */}";
  print "        <div className={`${cardClass} p-5 rounded-xl border space-y-4`}>";
  print "          <div className={`flex items-center justify-between border-b pb-3 ${isDark ? \"border-zinc-800\" : \"border-slate-100\"}`}>";
  print "            <div className=\"flex items-center gap-2\">";
  print "              <Layers className=\"w-4 h-4 text-rose-500\" />";
  print "              <h3 className={`font-bold text-xs tracking-wide uppercase ${isDark ? \"text-zinc-200\" : \"text-slate-800\"}`}>Lançador de Fármacos</h3>";
  print "            </div>";
  print "            <span className={`text-[10px] px-2 py-0.5 rounded font-mono font-medium ${isDark ? \"bg-rose-950/20 text-rose-300\" : \"bg-rose-50 text-rose-700\"}`}>";
  print "              Lançamento Rápido";
  print "            </span>";
  print "          </div>";
  print "";
  print "          <div className=\"flex flex-col gap-5\">";
  print "            {/* STAGING AREA */}";
  print "            <div className={`p-4 md:p-5 rounded-2xl border-2 transition-all duration-200 shadow-sm ${isDark ? \"bg-zinc-900/80 border-rose-900/50\" : \"bg-rose-50/50 border-rose-200\"}`}>";
  print "              <div className=\"flex flex-col lg:flex-row gap-5 lg:items-center\">";
  print "                ";
  print "                {/* Drug Info & Edit */}";
  print "                <div className=\"flex-1\">";
  print "                  <div className=\"flex items-center gap-2 mb-1\">";
  print "                    <h4 className={`text-xl font-black tracking-tight ${isDark ? \"text-zinc-100\" : \"text-slate-800\"}`}>";
  print "                      {selectedDrug.name}";
  print "                    </h4>";
  print "                    <button ";
  print "                      onClick={() => {";
  print "                        setDrugEditorMode(\"edit\");";
  print "                        setDrugEditorData(selectedDrug);";
  print "                        setShowDrugEditor(true);";
  print "                      }}";
  print "                      className=\"p-1.5 rounded-full text-slate-400 hover:text-rose-500 hover:bg-rose-100 dark:hover:bg-rose-950/50 transition-colors\"";
  print "                      title=\"Editar fármaco\"";
  print "                    >";
  print "                      <Edit2 className=\"w-4 h-4\" />";
  print "                    </button>";
  print "                  </div>";
  print "                  <div className={`text-xs font-bold uppercase tracking-wider ${isDark ? \"text-rose-400/80\" : \"text-rose-600/80\"}`}>";
  print "                    {selectedDrug.category || \"Outros\"}";
  print "                  </div>";
  print "                </div>";
  print "";
  print "                {/* Interactive Controls */}";
  print "                <div className=\"flex flex-wrap lg:flex-nowrap items-center gap-3\">";
  print "                  ";
  print "                  {/* Dose Control */}";
  print "                  <div className={`flex items-center p-1 rounded-xl border ${isDark ? \"bg-zinc-950 border-zinc-800\" : \"bg-white border-slate-200 shadow-sm\"}`}>";
  print "                    <button ";
  print "                      type=\"button\" ";
  print "                      onClick={() => {";
  print "                        const step = selectedDrug.defaultUnit === \"mcg\" ? 10 : (selectedDrug.defaultUnit === \"g\" ? 0.5 : 1);";
  print "                        setCustomDose(prev => String(Math.max(0, (parseFloat(prev || \"0\") - step))));";
  print "                      }} ";
  print "                      className={`w-12 h-12 flex items-center justify-center rounded-lg transition-colors active:scale-95 ${isDark ? \"bg-zinc-900 text-zinc-400 hover:bg-zinc-800\" : \"bg-slate-100 text-slate-600 hover:bg-slate-200\"}`}";
  print "                    >";
  print "                      <Minus className=\"w-6 h-6\" />";
  print "                    </button>";
  print "                    <div className=\"relative flex items-center justify-center w-24 h-12\">";
  print "                      <input";
  print "                         type=\"number\"";
  print "                         step=\"any\"";
  print "                         value={customDose}";
  print "                         onChange={(e) => setCustomDose(e.target.value)}";
  print "                         className=\"w-full h-full text-center font-black text-2xl bg-transparent border-none focus:ring-0 p-0 text-slate-800 dark:text-zinc-100\"";
  print "                      />";
  print "                    </div>";
  print "                    <span className={`text-sm font-bold mr-3 ${isDark ? \"text-zinc-500\" : \"text-slate-400\"}`}>{selectedDrug.defaultUnit}</span>";
  print "                    <button ";
  print "                      type=\"button\" ";
  print "                      onClick={() => {";
  print "                        const step = selectedDrug.defaultUnit === \"mcg\" ? 10 : (selectedDrug.defaultUnit === \"g\" ? 0.5 : 1);";
  print "                        setCustomDose(prev => String(parseFloat(prev || \"0\") + step));";
  print "                      }} ";
  print "                      className={`w-12 h-12 flex items-center justify-center rounded-lg transition-colors active:scale-95 ${isDark ? \"bg-zinc-900 text-zinc-400 hover:bg-zinc-800\" : \"bg-slate-100 text-slate-600 hover:bg-slate-200\"}`}";
  print "                    >";
  print "                      <Plus className=\"w-6 h-6\" />";
  print "                    </button>";
  print "                  </div>";
  print "";
  print "                  {/* Route Segmented Control */}";
  print "                  <div className={`flex p-1 rounded-xl border ${isDark ? \"bg-zinc-950 border-zinc-800\" : \"bg-slate-100 border-slate-200\"}`}>";
  print "                    {[\"EV\", \"IM\", \"SC\", \"VO\"].map(route => (";
  print "                      <button";
  print "                        key={route}";
  print "                        type=\"button\"";
  print "                        onClick={() => setCustomRoute(route)}";
  print "                        className={`px-4 py-3 text-sm font-bold rounded-lg transition-all ${customRoute === route ? \"bg-white dark:bg-zinc-800 text-rose-600 dark:text-rose-400 shadow-sm\" : \"text-slate-500 dark:text-zinc-500 hover:text-slate-700 dark:hover:text-zinc-300\"}`}";
  print "                      >";
  print "                        {route}";
  print "                      </button>";
  print "                    ))}";
  print "                  </div>";
  print "";
  print "                  {/* Time & Launch */}";
  print "                  <div className=\"flex w-full lg:w-auto gap-2\">";
  print "                    <input ";
  print "                      type=\"time\" ";
  print "                      value={customTime}";
  print "                      onChange={(e) => setCustomTime(e.target.value)}";
  print "                      className={`h-14 px-4 w-full lg:w-auto rounded-xl text-lg font-bold border transition-colors ${isDark ? \"bg-zinc-950 border-zinc-800 text-zinc-200 focus:border-rose-500\" : \"bg-white border-slate-200 text-slate-800 focus:border-rose-500\"}`}";
  print "                    />";
  print "                    <button";
  print "                      onClick={handleAddBolusDrug}";
  print "                      className=\"h-14 px-8 flex-1 lg:flex-none flex items-center justify-center gap-2 bg-rose-600 hover:bg-rose-700 text-white rounded-xl font-bold text-lg shadow-lg shadow-rose-500/25 active:scale-95 transition-all\"";
  print "                    >";
  print "                      <Check className=\"w-6 h-6\" />";
  print "                      <span>Lançar</span>";
  print "                    </button>";
  print "                  </div>";
  print "                </div>";
  print "              </div>";
  print "            </div>";
  print "";
  print "            {/* Visual Ampoule Status */}";
  print "            {(() => {";
  print "              const ampouleAmount = (selectedDrug as any).ampouleAmount;";
  print "              if (!ampouleAmount) return null;";
  print "              ";
  print "              const currentDrugBoluses = document.bolusDrugs?.filter(b => b.name === selectedDrug.name) || [];";
  print "              const totalDoseGiven = currentDrugBoluses.reduce((acc, b) => acc + b.dose, 0);";
  print "              ";
  print "              const currentAmpoules = Math.ceil(totalDoseGiven / ampouleAmount);";
  print "              ";
  print "              const newDose = parseFloat(customDose) || 0;";
  print "              const newTotalDose = totalDoseGiven + newDose;";
  print "              const newAmpoules = Math.ceil(newTotalDose / ampouleAmount);";
  print "              ";
  print "              const remainingInCurrentAmpoule = currentAmpoules > 0 ? (currentAmpoules * ampouleAmount) - totalDoseGiven : 0;";
  print "              const opensNewAmpoule = newAmpoules > currentAmpoules;";
  print "              ";
  print "              return (";
  print "                <div className={`p-3 rounded-xl border flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs transition-all ${";
  print "                  opensNewAmpoule ";
  print "                     ? (isDark ? \"bg-rose-950/20 border-rose-900/50 text-rose-200\" : \"bg-rose-50 border-rose-200 text-rose-800\")";
  print "                    : (isDark ? \"bg-zinc-900/50 border-zinc-800/60 text-zinc-300\" : \"bg-slate-50 border-slate-200 text-slate-600\")";
  print "                }`}>";
  print "                  <div className=\"flex items-center gap-4 font-medium\">";
  print "                    <div className=\"flex items-center gap-1.5\">";
  print "                      <Layers className={`w-4 h-4 ${opensNewAmpoule ? \"text-rose-500\" : \"text-zinc-400\"}`} />";
  print "                      <span>Ampola padrão: <strong className=\"text-sm\">{ampouleAmount} {selectedDrug.defaultUnit}</strong></span>";
  print "                    </div>";
  print "                    <span>Total infundido (paciente): <strong className=\"text-sm\">{totalDoseGiven} {selectedDrug.defaultUnit}</strong></span>";
  print "                  </div>";
  print "                  ";
  print "                  <div className=\"flex items-center justify-between sm:justify-end gap-4\">";
  print "                    <span className=\"opacity-90\">";
  print "                      {remainingInCurrentAmpoule > 0 ";
  print "                         ? `Restam ${remainingInCurrentAmpoule} ${selectedDrug.defaultUnit} na ampola aberta`";
  print "                        : \"Nenhuma ampola aberta com sobra\"";
  print "                      }";
  print "                    </span>";
  print "                    {newDose > 0 && (";
  print "                      <span className=\"font-bold flex items-center gap-1.5 text-[11px] uppercase tracking-wider\">";
  print "                        {opensNewAmpoule ? (";
  print "                          <>";
  print "                            <span className=\"w-2 h-2 rounded-full bg-rose-500 animate-pulse\"></span>";
  print "                            Vai abrir +{newAmpoules - currentAmpoules} ampola(s)";
  print "                          </>";
  print "                        ) : (";
  print "                          <>";
  print "                            <span className=\"w-2 h-2 rounded-full bg-emerald-500\"></span>";
  print "                            Dose na ampola atual";
  print "                          </>";
  print "                        )}";
  print "                      </span>";
  print "                    )}";
  print "                  </div>";
  print "                </div>";
  print "              );";
  print "            })()}";
  print "";
  print "            {/* Search & Filters */}";
  print "            <div className=\"flex flex-col md:flex-row gap-3 mt-2\">";
  print "              {/* Search */}";
  print "              <div className=\"relative flex-1\">";
  print "                <Search className={`absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 ${isDark ? \"text-zinc-500\" : \"text-slate-400\"}`} />";
  print "                <input";
  print "                  type=\"text\"";
  print "                  placeholder=\"Buscar fármaco...\"";
  print "                  value={drugSearchQuery}";
  print "                  onChange={(e) => setDrugSearchQuery(e.target.value)}";
  print "                  className={`w-full pl-10 pr-4 py-3 rounded-xl text-sm border font-medium transition-colors ${";
  print "                    isDark ";
  print "                      ? \"bg-zinc-900 border-zinc-800 text-zinc-200 focus:border-rose-500 focus:bg-zinc-950\" ";
  print "                      : \"bg-white border-slate-200 text-slate-800 focus:border-rose-500 focus:bg-slate-50\"";
  print "                  }`}";
  print "                />";
  print "              </div>";
  print "              ";
  print "              {/* Categories */}";
  print "              <div className=\"flex-1 overflow-x-auto hide-scrollbar\">";
  print "                <div className=\"flex gap-2 min-w-max pb-1 h-full items-center\">";
  print "                  {[\"Todos\", ...Array.from(new Set(allAvailableDrugs.map(d => d.category || \"Outros\"))).sort()].map(cat => (";
  print "                    <button";
  print "                      key={cat}";
  print "                      onClick={() => setSelectedDrugCategory(cat)}";
  print "                      className={`px-4 py-2.5 rounded-xl text-xs font-bold transition-colors whitespace-nowrap ${";
  print "                        selectedDrugCategory === cat";
  print "                          ? isDark";
  print "                            ? \"bg-zinc-800 text-zinc-100 shadow-sm\"";
  print "                            : \"bg-slate-800 text-white shadow-sm\"";
  print "                          : isDark";
  print "                            ? \"bg-zinc-900/50 text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200 border border-zinc-800/50\"";
  print "                            : \"bg-white text-slate-600 hover:bg-slate-100 border border-slate-200\"";
  print "                      }`}";
  print "                    >";
  print "                      {cat.split(\" / \")[0].split(\" e \")[0]}";
  print "                    </button>";
  print "                  ))}";
  print "                </div>";
  print "              </div>";
  print "              ";
  print "              <button";
  print "                onClick={() => {";
  print "                  setDrugEditorMode(\"create\");";
  print "                  setDrugEditorData({";
  print "                    name: \"\",";
  print "                    category: selectedDrugCategory !== \"Todos\" ? selectedDrugCategory : \"Outros\",";
  print "                    defaultDose: 0,";
  print "                    defaultUnit: \"mg\",";
  print "                    defaultRoute: \"EV\",";
  print "                    ampouleAmount: 0";
  print "                  } as any);";
  print "                  setShowDrugEditor(true);";
  print "                }}";
  print "                className={`flex-shrink-0 flex items-center justify-center w-12 h-12 rounded-xl transition-colors ${";
  print "                  isDark ";
  print "                    ? \"bg-zinc-900 border border-zinc-800 text-rose-400 hover:bg-zinc-800\" ";
  print "                    : \"bg-white border border-slate-200 text-rose-600 hover:bg-rose-50\"";
  print "                }`}";
  print "                title=\"Novo Fármaco\"";
  print "              >";
  print "                <Plus className=\"w-6 h-6\" />";
  print "              </button>";
  print "            </div>";
  print "";
  print "            {/* Grid of Drugs */}";
  print "            <div className=\"max-h-[350px] overflow-y-auto pr-2 scrollbar-thin\">";
  print "              <div className=\"grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-3\">";
  print "                {(() => {";
  print "                  const filteredDrugs = allAvailableDrugs.filter(drug => {";
  print "                    const matchesCategory = selectedDrugCategory === \"Todos\" || drug.category === selectedDrugCategory;";
  print "                    const matchesSearch = drug.name.toLowerCase().includes(drugSearchQuery.toLowerCase());";
  print "                    return matchesCategory && matchesSearch;";
  print "                  });";
  print "";
  print "                  if (filteredDrugs.length === 0) {";
  print "                    return (";
  print "                      <div className=\"col-span-full text-center py-10 space-y-2\">";
  print "                        <p className={`text-sm font-semibold ${isDark ? \"text-zinc-500\" : \"text-slate-400 dark:text-zinc-500\"}`}>";
  print "                          Nenhum fármaco encontrado.";
  print "                        </p>";
  print "                      </div>";
  print "                    );";
  print "                  }";
  print "";
  print "                  return filteredDrugs.map((drug, index) => {";
  print "                    const isCurrentlySelected = selectedDrug.name === drug.name;";
  print "                    return (";
  print "                      <button";
  print "                        key={index}";
  print "                        onClick={() => {";
  print "                          setSelectedDrug(drug);";
  print "                          setCustomDose(drug.defaultDose?.toString() || \"\");";
  print "                          setCustomRoute(drug.defaultRoute || \"EV\");";
  print "                          setCustomTime(formatToLocalTime(new Date(), \"America/Sao_Paulo\"));";
  print "                        }}";
  print "                        className={`flex flex-col items-start p-4 rounded-xl border text-left transition-all active:scale-95 ${";
  print "                          isCurrentlySelected";
  print "                            ? isDark";
  print "                              ? \"bg-rose-900/20 border-rose-500/80 shadow-md shadow-rose-900/20\"";
  print "                              : \"bg-rose-50 border-rose-400 shadow-md shadow-rose-100\"";
  print "                            : isDark";
  print "                              ? \"bg-zinc-900/60 border-zinc-800 hover:bg-zinc-800 hover:border-zinc-700\"";
  print "                              : \"bg-white border-slate-200 hover:bg-slate-50 hover:border-slate-300 shadow-sm\"";
  print "                        }`}";
  print "                      >";
  print "                        <span className={`text-sm font-black line-clamp-1 mb-1.5 w-full truncate ${";
  print "                          isCurrentlySelected ";
  print "                            ? (isDark ? \"text-rose-400\" : \"text-rose-700\")";
  print "                            : (isDark ? \"text-zinc-200\" : \"text-slate-700\")";
  print "                        }`}>";
  print "                          {drug.name}";
  print "                        </span>";
  print "                        ";
  print "                        <div className=\"flex items-center justify-between w-full mt-auto pt-2\">";
  print "                          <span className={`text-[11px] font-bold ${";
  print "                            isCurrentlySelected";
  print "                              ? (isDark ? \"text-rose-300\" : \"text-rose-600\")";
  print "                              : (isDark ? \"text-zinc-400\" : \"text-slate-500\")";
  print "                          }`}>";
  print "                            {drug.defaultDose} {drug.defaultUnit}";
  print "                          </span>";
  print "                          <span className={`text-[10px] px-1.5 py-0.5 rounded-md font-bold ${";
  print "                            isCurrentlySelected";
  print "                              ? isDark ? \"bg-rose-900/50 text-rose-300\" : \"bg-rose-100 text-rose-700\"";
  print "                              : isDark ? \"bg-zinc-800 text-zinc-400\" : \"bg-slate-100 text-slate-500\"";
  print "                          }`}>";
  print "                            {drug.defaultRoute || \"EV\"}";
  print "                          </span>";
  print "                        </div>";
  print "                      </button>";
  print "                    );";
  print "                  });";
  print "                })()}";
  print "              </div>";
  print "            </div>";
  print "          </div>";
  print "        </div>";
  next;
}
/{[/]\* RESUMO DE FÁRMACOS ADMINISTRADOS \*\// {
  skip = 0;
}
!skip {
  print $0;
}
' src/components/IntraoperativeTab.tsx > tmp.tsx && mv tmp.tsx src/components/IntraoperativeTab.tsx
