const CANONICAL_DRUG_NAMES = [
  "Propofol",
  "Etomidato",
  "Cetamina",
  "Midazolam",
  "Tiopental",
  "Dexmedetomidina",
  "Diazepam",
  "Rocurônio",
  "Atracúrio",
  "Cisatracúrio",
  "Succinilcolina",
  "Pancurônio",
  "Fentanil",
  "Sufentanil",
  "Remifentanil",
  "Alfentanil",
  "Morfina",
  "Tramadol",
  "Nalbufina",
  "Adrenalina",
  "Noradrenalina",
  "Dobutamina",
  "Dopamina",
  "Milrinona",
  "Efedrina",
  "Metaraminol",
  "Fenilefrina",
  "Vasopressina",
  "Atropina",
  "Amiodarona",
  "Esmolol",
  "Clonidina",
  "Hidralazina",
  "Adenosina",
  "Metoprolol",
  "Nitroglicerina",
  "Nitroprussiato de Sódio",
  "Ondansetrona",
  "Dexametasona",
  "Metoclopramida",
  "Droperidol",
  "Cefazolina",
  "Lidocaína",
  "Dipirona",
  "Cetoprofeno",
  "Cetorolaco",
  "Parecoxibe",
  "Tenoxicam",
  "Sugamadex",
  "Neostigmina",
  "Flumazenil",
  "Naloxona",
  "Furosemida",
  "Gluconato de Cálcio",
  "Hidrocortisona",
  "Bicarbonato de Sódio",
  "Ácido Tranexâmico",
  "Tranexâmico",
  "Ocitocina",
  "Insulina Regular",
  "Bupivacaína",
  "Ropivacaína",
  "Sevoflurano",
  "Desflurano",
  "Isoflurano",
  "Óxido Nitroso",
  "Oxigênio",
  "Ar comprimido",
] as const;

const SPOKEN_ALIASES = [
  "fenta",
  "remi",
  "sufenta",
  "nora",
  "norinha",
  "sevo",
  "des",
  "iso",
  "keta",
  "rocu",
  "esmeron",
  "nimbium",
  "precedex",
  "adrena",
  "atropo",
] as const;

export function transcriptionVocabulary(limit = 100): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const term of [...CANONICAL_DRUG_NAMES, ...SPOKEN_ALIASES]) {
    const key = term.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(term);
    if (out.length >= limit) break;
  }
  return out;
}
